"""add Message table

Revision ID: e5d1559249e8
Revises: 390d397620db
Create Date: 2025-05-02 12:24:24.404341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5d1559249e8'
down_revision: Union[str, None] = '390d397620db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'messages', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('messages', 'timestamp')
    # ### end Alembic commands ###
